server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# ─── User Service (Auth - public) ───
spring.cloud.gateway.mvc.routes[0].id=user-service-auth
spring.cloud.gateway.mvc.routes[0].uri=lb://user-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**

# ─── User Service (Profile - secured) ───
spring.cloud.gateway.mvc.routes[1].id=user-service
spring.cloud.gateway.mvc.routes[1].uri=lb://user-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/users/**

# ─── Operator Service ───
spring.cloud.gateway.mvc.routes[2].id=operator-service
spring.cloud.gateway.mvc.routes[2].uri=lb://operator-service
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/operators/**

# ─── Recharge Service ───
spring.cloud.gateway.mvc.routes[3].id=recharge-service
spring.cloud.gateway.mvc.routes[3].uri=lb://recharge-service
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/recharges/**

# ─── Payment Service ───
spring.cloud.gateway.mvc.routes[4].id=payment-service
spring.cloud.gateway.mvc.routes[4].uri=lb://payment-service
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/payments/**

# ─── Notification Service ───
spring.cloud.gateway.mvc.routes[5].id=notification-service
spring.cloud.gateway.mvc.routes[5].uri=lb://notification-service
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/notifications/**


# Zipkin Distributed Tracing
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

app.jwt.secret=omnicharge-secret-key-must-be-at-least-32-chars-long

management.endpoints.web.exposure.include=*
