server.port=8080

# EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# AUTH SERVICE
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/auth/**

# ADMIN SERVICE
spring.cloud.gateway.mvc.routes[1].id=admin-service
spring.cloud.gateway.mvc.routes[1].uri=lb://USERSERVICE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/admin/**

# OPERATOR SERVICE
spring.cloud.gateway.mvc.routes[2].id=operator-service
spring.cloud.gateway.mvc.routes[2].uri=lb://OPERATORSERVICE
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/operator/**

# RECHARGE SERVICE
spring.cloud.gateway.mvc.routes[3].id=recharge-service
spring.cloud.gateway.mvc.routes[3].uri=lb://RECHARGESERVICE
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/recharges/**

spring.cloud.gateway.mvc.routes[6].id=user-profile-service
spring.cloud.gateway.mvc.routes[6].uri=lb://USERSERVICE
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/user/**


# PAYMENT SERVICE
spring.cloud.gateway.mvc.routes[4].id=payment-service
spring.cloud.gateway.mvc.routes[4].uri=lb://PAYMENTSERVICE
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/payments/**

# NOTIFICATION SERVICE
spring.cloud.gateway.mvc.routes[5].id=notification-service
spring.cloud.gateway.mvc.routes[5].uri=lb://NOTIFICATIONSERVICE
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/notifications/**

# GLOBAL CORS
spring.cloud.gateway.mvc.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.mvc.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.mvc.globalcors.cors-configurations.[/**].allowedHeaders=*

# LOGGING
logging.level.org.springframework.cloud.gateway=DEBUG
